productos/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('',views.about_page,name="about_page"),
    path('productos/',views.productos_page,name="productos_page"),
    path('productos/busqueda/',views.producto_busqueda,name="producto_busqueda"),
    path('productos/<slug:categoria_slug>/',views.productos_page, name='productos_por_categoria'),
    path('productos/detalles/<int:id>/<slug:producto_slug>/',views.producto_detalles, name='producto_detalles'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponseRedirect

from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',lambda r : HttpResponseRedirect('store')),
    path('store/', include("productos.urls",namespace="store"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/models.py
from django.db import models
from django.urls import reverse

class Categoria(models.Model):
    nombre =  models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)


    class Meta:
        ordering=('nombre',)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('store:productos_por_categoria',args=[self.slug])    


class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,related_name="categoria",on_delete= models.CASCADE)
    nombre =   models.CharField(max_length=200,db_index=True)
    slug= models.SlugField(max_length=200,db_index=True)
    imagen =models.ImageField(upload_to="productos/%Y/%m/%d",blank=True)
    descripcion = models.TextField(blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    almacen = models.PositiveIntegerField()
    disponibilidad = models.BooleanField(default=False)
    creado =  models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
   
    class Meta:
        ordering = ('nombre',)
        index_together= (('id','slug'))

    def __str__(self):
        return self.nombre 

    def get_absolute_url(self):
        return reverse("store:producto_detalles",args=[self.id,self.slug])
        

productos/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder': 'Busqueda'}))

productos/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.postgres.search import SearchVector
from .models import Categoria,Producto
from .forms import SearchForm

# Create your views here.

def about_page(request):
    name = "Tienda virtual"
    context= {"name": name }
    return render(request,'productos/about.html',context)

def productos_page(request,categoria_slug=None):
    categoria= None
    categorias = Categoria.objects.all()
    productos= Producto.objects.filter(disponibilidad=True)
    if categoria_slug :
        categoria = get_object_or_404(categorias,slug=categoria_slug)
        productos = productos.filter(categoria=categoria)
    
    paginator= Paginator(productos,8)
    page= request.GET.get('page')

    try: 
        items= paginator.page(page)
    except PageNotAnInteger: 
           items = paginator.page(1) 
    except EmptyPage:
            items = paginator.page(paginator.num_pages)
        

    context = {"categoria": categoria ,"categorias": categorias,"items": items }
    return render(request,"productos/posts/list.html",context)


def producto_detalles(request,id,producto_slug):

    productos = Producto.objects.all()
    producto = get_object_or_404(productos,id=id,slug=producto_slug) 
   
    context = { "producto": producto}
    return render(request,"productos/posts/detalles.html",context)


def producto_busqueda(request):
    form = SearchForm()
    query = None
    results=[]
    if request.method == 'GET':
        form= SearchForm(request.GET)
        if form.is_valid():
            query= form.cleaned_data['query']
            results= Producto.objects.annotate(search=SearchVector('nombre','slug'),).filter(search=query)

    context = {"form" : form,"query":query,"results": results}
    return render(request,"productos/posts/busqueda.html",context)

productos/templates/pagination.html
   {% if page.has_previous %}
     <a class="btn btn-outline-info mb-4" href="?page=1">Primero</a>
     <a class="btn btn-outline-info mb-4" href="?page={{ page.previous_page_number }}">Anterior</a>
   {% endif %}

   {% for num in page.paginator.page_range %}
      {% if page.number == num %}
           <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif  num  > page.number|add:'-3' and num < page.number|add:'3' %}
             <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
   {% endfor %}
   
   {% if page.has_next %}
     <a class="btn btn-outline-info mb-4" href="?page={{ page.next_page_number }}">Siguiente</a>
     <a class="btn btn-outline-info mb-4" href="?page={{ page.paginator.num_pages }}">Ultimo  </a>
   {% endif %}

productos/templates/productos/about.html
{% extends 'productos/base.html' %} 
{% load static %} 

{% block content %}


  <div class="w-100  wall">
    <div class="titulo">
        <p class="principal">Somos los primeros!</p>
    </div>
   <div class="row justify-content-center">

    <div
      id="carouselExampleIndicators"
      class="carousel slide"
      data-ride="carousel"
      style="box-shadow : 10px 10px 20px black;border-radius: 20px; overflow: hidden;width:60%"
    >
      <ol class="carousel-indicators">
        <li
          data-target="#carouselExampleIndicators"
          data-slide-to="0"
          class="active"
        ></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img
            src="{% static 'productos/cafes.jpg'%}"
            class="d-block w-100"
            alt="..."
    
          />
            <div class="carousel-caption d-none d-md-block">
              <h5>Esperanza</h5>
              <p>Es todo lo que se necesita en esta vida</p>
            </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'productos/cafes2.jpg'%}"
            class="d-block w-100"
            alt="..."
     
          />
              <div class="carousel-caption d-none d-md-block">
              <h5>Ilusion</h5>
              <p>El cambio esta en eso</p>
            </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'productos/cafes3.jpg'%}"
            class="d-block w-100"
            alt="..."
    
          />
              <div class="carousel-caption d-none d-md-block">
              <h5>Superposicion</h5>
              <p>En esto radica nuestra esperanza</p>
            </div>
        </div>


      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleIndicators"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleIndicators"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

   </div>

  </div>

{% endblock %}

productos/templates/productos/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'productos/css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
   <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark  fixed-top fondonav" >
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'store:productos_page' %}">Tienda Virtual</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
          
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'store:about_page' %}">ABOUT</a>
              <a class="nav-item nav-link" href="{% url 'store:productos_page' %}">PRODUCTOS</a>
              <a class="nav-item nav-link" href="{% url 'store:producto_busqueda' %}"><i  style="font-size : 25px" class="fas fa-search"></i></a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="w-100">
      <div class="row" style="margin-right:0; margin-left:0">
          {% block content %}{% endblock %}
      </div>
    </main>  

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

productos/templates/productos/posts/busqueda.html
{% extends 'productos/base.html' %}
{% load static %}
{% block content %}
   <div class="contenedor w-100" style="margin-top: 80px">
         {% if query %}
        <h3>Elementos que coinciden con :  {{ query }}</h3>
        <h3>
            {% with results.count as total_results %}
               Encontrados:  {{ total_results}} 
            {% endwith %}
        </h3>
        
   <div class="row w-100" style="margin-left: 0; margin-right:0">
                  
    
             {% for  result in results %}
                   
                        <div class="col-md-3" style="margin-bottom :20px;">
                        <a href="{{ result.get_absolute_url }}" style="text-decoration :none;">
                            <div class="card" style="width: 100% ; height : 400px">
                            <img   {% if result.imagen %} 
                                        src="{{ result.imagen.url }}"
                                    {% else %} src="{% static 'productos/Noimage.jpg' %}"
                                    {% endif %}  class="card-img-top" height="250px" width="250px">
                            <div class="card-body">
                                <h5 class="card-title">{{ result.nombre}}</h5>
                                <p class="card-text">Precio:MXN${{ result.precio}}</p>
                            </div>
                        </div>
                        </a>
                       </div> 
                 {% empty %}
                 <p>No hay resultados de la busqueda.</p>        
                     
             {% endfor %}
     
   </div>

   {% else %}
    <form action="." method="GET" class="w-100">
    
            <div class="form-group">
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-group has-search">

                                <span class="fa fa-search form-control-feedback"></span>
                                {{ form.query }}
                        
                        
                        </div>    
                    </div>
            </div>

                <div class="row">
                    <div class="col-12 col-md-2">
                        <div class="form-group ">
                            <input  class="form-control" type="submit" value="Buscar">
                        </div>    
                    </div>
            </div>

        
            
            </div>
   </form>

   {% endif %}
   
   </div>
  
{% endblock content %}


   

productos/templates/productos/posts/detalles.html
{% extends 'productos/base.html' %}
{% block title %}Detalles{% endblock %}

{% block content %}
      <article class="media content-section" style="margin-top :60px">
           
            <div class="media-body">
                
                <div class="article-metadata">
                        <h3 style="text-align:center;">{{ producto.nombre }}</h3>
                </div>

               <div class="row">
                 <div class="col-md-6">
                           <img {% if producto.imagen %} 
                            src="{{ producto.imagen.url }}"
                            {% else %} src="{% url 'productos/Noimage.jpg' %}"  
                            {% endif %}  class="img-fluid" alt="Responsive image"
                        style="margin-bottom : 10px; height :450px">
                 
                 </div>
                 <div class="col-md-6">
                         <p class="article-content">{{ producto.descripcion }}</p>
                         <h4>Precio: MXN${{ producto.precio }}</h4>
                 </div>
               
               </div>
           
            </div>


        </article>
 {% endblock %}       

productos/templates/productos/posts/list.html
{% extends 'productos/base.html' %}
{% load static %}
{% block title %} Lista {% endblock%}

{% block content %}
   <div class="row w-100 justify-content-center" style="margin-top : 60px ;margin-left: 0; margin-right:0">
      <div class="col-md-6">
        <div class="content-section">
            <h3 style="text-align: center">CATEGORIAS</h3>      
            <ul style="text-align:center">        
                <li  style="display : inline-block" {% if categoria %} class="list-group-item list-group-item-light"{% else %}class="list-group-item list-group-item-light selected"{% endif%}>
                <a  style="text-decoration :none; font-family: 'Merienda', cursive;
                font-size: 1rem;" 
                href="{% url 'store:productos_page'%}">Todos</a>
                </li>
                
                {% for c in categorias %}
                    <li style="display : inline-block" {% if categoria.slug == c.slug  %} 
                    class="list-group-item list-group-item-light selected" 
                    {% else %} 
                    class="list-group-item list-group-item-light" 
                    {% endif %}>
                    <a style="text-decoration :none; font-family: 'Merienda', cursive;
                    font-size: 1rem;" href="{{ c.get_absolute_url}}">{{ c.slug }}</a>
                    </li>
                {% endfor %}

            
            </ul>     
        </div>
    </div>
    

   </div>
   
   <div class="row w-100" style="margin-left: 0; margin-right:0">
                  
    
             {% for  item in items %}
                   
                        <div class="col-md-3" style="margin-bottom :20px;">
                        <a href="{{ item.get_absolute_url }}" style="text-decoration :none;">
                            <div class="card" style="width: 100% ; height : 400px">
                            <img   {% if item.imagen %} 
                                        src="{{ item.imagen.url }}"
                                    {% else %} src="{% static 'productos/Noimage.jpg' %}"
                                    {% endif %}  class="card-img-top" height="250px" width="250px">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.nombre}}</h5>
                                <p class="card-text">Precio:MXN${{ item.precio}}</p>
                            </div>
                        </div>
                        </a>
                       </div> 
                     
             {% endfor %}
     
   </div>

<div class="w-100" style="margin-top : 20px; text-align:center">
    {% include 'pagination.html' with page=items %}
</div>

  



    
 


{% endblock content %}